### PR TITLE
Fixed color of AvatarImageView

### LINKED ISSUE #4: Store the color of AvatarImageView
**Describe the feature you'd like**
Currently, the color of AvatarImageView gets change every time when the view is recreated. So for every profile assign a color by picking up a color randomly from the list of colors(which is already present in code), store it in the database and set that color to the AvatarImageView.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #4 

Changes: Earlier, the color of AvatarImageView used to get changed every time when the view was recreated or the app theme was changed from light mode to dark mode(or vice versa). Now that is fixed.

There is no need to uninstall previous version of app.

Apart from that the data of profiles created earlier doesn't gets affected after the changes.  

Screenshots for the change: 

<table>
  <tr>
    <td></td>
    <td></td>
</tr>
</table>

### CODE REVIEW

File: app/src/main/java/com/rob729/quiethours/Fragments/NewProfileFragment.kt [hunk 1]
```diff
@@ -130,7 +132,8 @@ class NewProfileFragment : Fragment() {
                     smin = smin,
                     ehr = ehr,
                     emin = emin,
-                    d = daySelected.toJson(days)
+                    d = daySelected.toJson(days),
+                    c = col
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Fragments/NewProfileFragment.kt]: Why declare a variable col when it is only being used once and can be directly assigned to c?

File: app/src/main/java/com/rob729/quiethours/Database/Profile.kt [hunk 2]
```diff
@@ -14,6 +14,7 @@ data class Profile(
     var smin: Int,
     var ehr: Int,
     var emin: Int,
-    var d: String
+    var d: String,
+    var c: Int
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Database/Profile.kt]: Please rename the variable to a more comprehendible name, so that other contributors easily get to understand the purpose of this variable.

**Review by rob729 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/rob729/quiethours/Database/Profile.kt (hunk 2 above)
Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Database/Profile.kt]: okay, I will do so

File: app/src/main/java/com/rob729/quiethours/Fragments/NewProfileFragment.kt (hunk 1 above)
Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Fragments/NewProfileFragment.kt]: Ok, I will directly assign this

**Comment by coder2699** [comment]
@rob729 I have done the changes that were asked to make

File: app/src/main/java/com/rob729/quiethours/Database/Profile.kt [hunk 3]
```diff
@@ -14,6 +14,8 @@ data class Profile(
     var smin: Int,
     var ehr: Int,
     var emin: Int,
-    var d: String
+    var d: String,
+    // To store profile color in the database
+    var color_index: Int
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Database/Profile.kt]: @coder2699 Just one small change.
Change the name format from the snake case to the camel case.
Rest looks good to me

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Database/Profile.kt]: @Rob will the variable name "colorIndex" work?

Comment (rob729) [reply app/src/main/java/com/rob729/quiethours/Database/Profile.kt]: Yes

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Database/Profile.kt]: @rob729 done 👍

**Review by rob729 — APPROVED** [review]
