### PR TITLE
Fixed Dark mode bug

### LINKED ISSUE #45: Dark mode bug
**Describe the bug**
When the system dark mode is active on a device and the user opens the app after installing it then the status bar text color is black and the background color is also dark.

**To Reproduce**
1. Enable dark mode on android device.
2. Install the app.
3. Open the app.
4. Give permissions.
5. Go back to the app.

**Expected behavior**
The app should set the value of dark mode according to the system. If the system dark mode is enabled then the app should enable dark mode automatically and the value of shared preference of dark mode should also be changed accordingly.
This has to be done only when the app is opened for the first time.

**Screenshots**
 

**Smartphone Info:**
Android version: Android 10

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #45 

Changes:
<ul>
<li>
Created FIRST_BOOT to store boolean value as sharedpreference in order to check app was pre-installed or not.
</li>
<li>
Created IS_DARK to store sharedpreference value as true if the system was set to Dark mode at the time of app installation (or app data reset)</li>
<li>
checkFirstRun() in MainActivity checks whether app is installing for first time or it was pre-installed. It also does the work when app data is reset.</li>
<li>If system dark mode is on at the time of installation, the value of Dark mode in Settings.kt gets set to true.</li>
</ul>

Screenshots:
<table>
<tr>
<td>

</td>
</tr>
</table>

### CODE REVIEW

**Comment by coder2699** [comment]
@rob729 Please have a look at the PR.

File: app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt [hunk 1]
```diff
@@ -38,4 +44,15 @@ class MainActivity : AppCompatActivity() {
         val navController = myNavHostFragment.view?.let { Navigation.findNavController(it) }
         return navController!!.navigateUp() || super.onSupportNavigateUp()
     }
+
+    fun checkFirstRun() {
+        // Get current version code
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt]: instead of this slightly complex implementation, you could have used a shared pref by the name "firstRun"/"firstBoot". On the first time opening the app, the value will be false as it will not be present in the database and after the first run set the value to true.
Also, try to shift this code to the splash screen and see if it works fine.
It will help in distributing the code among different files.

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt]: @rob729 Thanks for your suggestion.
I have pushed the updated code reflecting upon the same.
Also, I have put checkFirstRun() in SplashScreen, it's working fine.

File: app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt [hunk 2]
```diff
@@ -24,11 +25,13 @@ class MainActivity : AppCompatActivity() {
         )
         supportActionBar?.elevation = 0F
         val appSharedPrefs = PreferenceManager.getDefaultSharedPreferences(applicationContext)
-        if (appSharedPrefs.getBoolean("nightMode", false)) {
+        if (appSharedPrefs.getBoolean("nightMode", StoreSession.readBoolean(AppConstants.IS_DARK))) {
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt]: what is the use of AppConstants.IS_DARK shared pref when "nightMode" is already there?
Use only "nightMode" shared pref and implement the same.
Also, improve the code used for "nightMode" shared pref like other shared prefs used in the app.

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt:28]: @rob729 I am able to use nightMode in place of IS_DARK. Just one question, while improving the code like other shared prefs, appSharedPrefs is of type getDefaultSharedPreferences, whereas StoreSession is taking getSharedPreferences. So where shall I put it?

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Activity/MainActivity.kt]: @rob729 I have made the changes that were asked. Please have a look

File: app/src/main/java/com/rob729/quiethours/util/StoreSession.kt [hunk 3]
```diff
@@ -30,6 +32,16 @@ object StoreSession {
         return sharedPreferences.getInt(key, 0)
     }
 
+    fun writeBoolean(key: String, value: Boolean) {
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/util/StoreSession.kt]: This implementation will cause problems in the future as when a boolean value will be required to store in shared pref it will be stored under appSharedPrefs instead of sharedPreferences.
Revert the appSharedPrefs implementation.

Comment (rob729) [reply app/src/main/java/com/rob729/quiethours/util/StoreSession.kt]: Or do one thing. Make it a more specific one. Instead of writeBoolean make it setNightMode and getNightMode.

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/util/StoreSession.kt:35]: Ok

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/util/StoreSession.kt]: @rob729 Done

File: app/src/main/java/com/rob729/quiethours/Activity/SplashScreen.kt [hunk 4]
```diff
@@ -12,6 +15,13 @@ class SplashScreen : AppCompatActivity() {
         val intent = Intent(this, MainActivity::class.java)
         startActivity(intent)
         overridePendingTransition(R.anim.fade_in, R.anim.fade_out)
+        checkFirstRun()
         finish()
     }
+    fun checkFirstRun() {
+        if (!StoreSession.getNightMode(AppConstants.FIRST_BOOT)) {
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Activity/SplashScreen.kt]: what is the logic of getting AppConstants.FIRST_BOOT from StoreSession.getNightMode() ?

File: app/src/main/java/com/rob729/quiethours/Activity/SplashScreen.kt [hunk 5]
```diff
@@ -12,6 +15,13 @@ class SplashScreen : AppCompatActivity() {
...
+            StoreSession.setNightMode(AppConstants.NIGHT_MODE, resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK == Configuration.UI_MODE_NIGHT_YES)
+        }
+        StoreSession.setNightMode(AppConstants.FIRST_BOOT, true)
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Activity/SplashScreen.kt]: same comment as above

File: app/src/main/java/com/rob729/quiethours/util/StoreSession.kt [hunk 6]
```diff
@@ -30,6 +32,16 @@ object StoreSession {
         return sharedPreferences.getInt(key, 0)
     }
 
+    fun setNightMode(key: String, value: Boolean) {
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/util/StoreSession.kt]: when you already know that this function will be used to set night mode then take the key as a function parameter?

File: app/src/main/java/com/rob729/quiethours/util/StoreSession.kt [hunk 7]
```diff
@@ -30,6 +32,16 @@ object StoreSession {
...
+        val editor = appSharedPrefs.edit()
+        editor?.putBoolean(key, value)
+        editor?.apply()
+    }
+
+    fun getNightMode(key: String): Boolean {
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/util/StoreSession.kt]: same comment as above.

**Review by rob729 — APPROVED** [review]

**Comment by rob729** [comment]
give @coder2699 25 points
