### PR TITLE
Fixed Vibration Mode Bug

### LINKED ISSUE #34: Fix Vibration Mode
**Describe the bug**
When a user has made two profiles A(10:00 AM - 12:00 PM) and B(11:00 AM - 1:00 PM) for the same day then at 12:01 PM, when profile A ends the phone audio profile changes to Normal. But instead it should switch the audio profile as set for profile B. 

**Expected behavior**
According to above given scenario, at 12:01PM, the phone audio settings should be same as set in profile B.  

- [ ] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #34 
Changes: With reference to the scenario that is mentioned, at 12:01 PM,  audio profile will get set according to profile B

### CODE REVIEW

File: app/src/main/java/com/rob729/quiethours/util/EndAlarm.kt [hunk 1]
```diff
@@ -24,8 +24,15 @@ class EndAlarm(appContext: Context, workerParams: WorkerParameters) :
 
         val audioManager =
             applicationContext.getSystemService(Context.AUDIO_SERVICE) as AudioManager
-        audioManager.ringerMode = AudioManager.RINGER_MODE_NORMAL
         StoreSession.writeInt(AppConstants.BEGIN_STATUS, StoreSession.readInt(AppConstants.BEGIN_STATUS) - 1)
+        if (StoreSession.readInt(AppConstants.BEGIN_STATUS)> 0) {
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/util/EndAlarm.kt]: Change it to audioManager.ringerMode = if...

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/util/EndAlarm.kt]: Done

**Review by rob729 — APPROVED** [review]

**Comment by rob729** [comment]
give @coder2699 75 points
