### PR TITLE
Ringtone fixed when Profile deleted

### LINKED ISSUE #49: Restore system audio when active profile is deleted
**Describe the bug**
When an active profile is deleted, the ringtone mode remains to be in vibration/silent state. Fix this, so that when an active profile is deleted ringtone mode becomes normal.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #49 

Changes: Now when an active profile is deleted the original ringtone state gets restored

APK link to test app: https://drive.google.com/file/d/1X-yZoZ36bVrfasNn_zQjFri7crCw8NLR/view?usp=sharing

### CODE REVIEW

**Comment by coder2699** [comment]
@rob729 Please have a look at this PR

File: app/src/main/java/com/rob729/quiethours/Fragments/MainFragment.kt [hunk 1]
```diff
@@ -50,7 +52,7 @@ class MainFragment : Fragment() {
     private val MY_REQUEST_CODE = 111
     val notificationManager =
         context?.getSystemService(NOTIFICATION_SERVICE) as NotificationManager?
-
+    val audioManager by lazy { activity?.getSystemService(Context.AUDIO_SERVICE) as AudioManager }
```
Comment (rob729) [inline app/src/main/java/com/rob729/quiethours/Fragments/MainFragment.kt]: instead of activity use requireActivity to avoid null check.

Comment (coder2699) [reply app/src/main/java/com/rob729/quiethours/Fragments/MainFragment.kt]: @rob729 Ok

**Review by rob729 — APPROVED** [review]

**Comment by rob729** [comment]
give @coder2699 25 points
